### ISSUE TITLE
Why are AndroidX changes not released?

### ISSUE THREAD

**Issue by WolandPL** [novoda/view-pager-adapter#21]
We're removing all android-support libraries from our project. view-pager-adapter is one of them. You have code changes migrating it to AndroidX but they are not included in any official release - why is that?

**Comment by ataulm** [comment]
The folks working on this actively left the company a while back. @Mecharyry can you make a release pls?

**Comment by WolandPL** [comment]
> The folks working on this actively left the company a while back. @Mecharyry can you make a release pls?

That would be awesome. Would that be also possible for landing-strip? We use both.

**Comment by juankysoriano** [comment]
Closing as this repository is no longer under maintenance and it's about to be archived
