### ISSUE TITLE
It's not always necessary to implement bindView but library forces me to

### ISSUE THREAD

**Issue by ataulm** [novoda/view-pager-adapter#4]
My viewpager uses completely different static layouts for each page (it's just for onboarding) - there is no data to bind.

Perhaps the `bindView` can just be an empty protected method instead of abstract?

**Comment by ouchadam** [comment]
if the view pager has static pages I would argue that this library wouldn't be needed

**Comment by ataulm** [comment]
The library provides a View implementation of PagerAdapter for use with ViewPager - whether the data is static or not seems irrelevant -> you'd still need a PagerAdapter that could create the correct View for a given position.

**Comment by ataulm** [comment]
We're reverting this in #18. It's pretty simple for the client to do, and if there's enough of a need (i.e. something _more_ than just an empty `bindView`), we can add another adapter implementation that makes it easier.
