### ISSUE TITLE
Pass a parameter in createView to let clients know the view has been restored

### ISSUE THREAD

**Issue by ouchadam** [novoda/view-pager-adapter#7]
Much like `Activity.onCreate(instanceState)`, the instance state is used to determine if the activity has been restored or is fresh, it would be useful to have the same behaviour in `createView`.

**Comment by blundell** [comment]
if i wanted to fix this issue for you, explaining what

> it would be useful to

would really help, in creating a demo etc

what does _useful_ actually mean?
